export type CustomGroup = "data-viz" | "feedback" | "input" | "layout" | "display" | "agentic";

export interface CustomCategory {
  id: CustomGroup;
  label: string;
  blurb: string;
}

export const CATEGORIES: CustomCategory[] = [
  {
    id: "data-viz",
    label: "data-viz",
    blurb: "Charts and plots rendered in character cells — line, bar, pie, gauge, heatmap and more.",
  },
  {
    id: "feedback",
    label: "feedback",
    blurb: "Progress, status and notification primitives that keep the user informed.",
  },
  {
    id: "input",
    label: "input",
    blurb: "Keyboard-driven interactive controls: editors, trees, dialogs.",
  },
  {
    id: "layout",
    label: "layout",
    blurb: "Structural helpers for arranging terminal UI.",
  },
  {
    id: "display",
    label: "display",
    blurb: "Presentational one-offs that render read-only content.",
  },
  {
    id: "agentic",
    label: "agentic",
    blurb: "Building blocks for AI-agent CLIs: spinners, tool calls, approvals, token meters.",
  },
];

export interface CustomVariant {
  id: string;
  label: string;
  blurb: string;
}

export interface CustomMeta {
  slug: string;
  name: string;
  description: string;
  accent: string;
  group: CustomGroup;
  source: string;
  demo: string;
  api: string;
  keymap: [string, string][];
  props: { name: string; type: string; default: string; description: string }[];
  notes: string[];
  variants?: CustomVariant[];
}

export const customComponents: CustomMeta[] = [
  {
    slug: "line-chart",
    name: "LineChart",
    description: "Multi-row line chart with gradient fill, reveal and crosshair",
    accent: "text-term-cyan",
    group: "data-viz",
    source: "line-chart.tsx",
    demo: "LineChart",
    api: "Half-block line renderer (▀▄█) with 2× vertical resolution per row. Bucket-downsamples when points exceed width. Keyboard navigation via useKeyboard; gate on `focused`.",
    keymap: [
      ["← / h", "Move crosshair left"],
      ["→ / l", "Move crosshair right"],
      ["(crosshair)", "Shows value + delta tooltip row"],
    ],
    props: [
      { name: "data", type: "number[] | {x,y}[]", default: "[]", description: "Series; auto-indexed when plain numbers" },
      { name: "width / height", type: "number", default: "40 / 10", description: "Chart area in characters" },
      { name: "color", type: "string", default: '"#7dcfff"', description: "Line color" },
      { name: "fill", type: "string", default: '"#1a1b26"', description: "Gradient end color under the line" },
      { name: "min / max", type: "number", default: "auto", description: "Fixed scale bounds" },
      { name: "title", type: "string", default: "-", description: "Optional header row with hi/lo labels" },
      { name: "loading", type: "boolean", default: "false", description: "Shimmer sweep skeleton" },
      { name: "reveal", type: "number", default: "1", description: "0..1 clip-reveal progress" },
      { name: "dots", type: "boolean", default: "true", description: "· at each data column on the line" },
      { name: "crosshair", type: "boolean", default: "false", description: "Enable selection + tooltip row" },
      { name: "focused", type: "boolean", default: "true", description: "Gate for keyboard handling" },
      { name: "selected / onSelect", type: "number | (i) => void", default: "-", description: "Controlled column selection" },
      { name: "format", type: "(v, i) => string", default: "-", description: "Tooltip value formatter" },
    ],
    notes: [
      "Gradient depth: cells below the line lerp `color → fill` by distance — the bklit area look.",
      "Loading renders a traveling ▓ sweep across the chart area, driven by an internal interval.",
      "Feed `reveal` from useTimeline for a scrubbed grow-in, or animate externally.",
    ],
  },
  {
    slug: "area-chart",
    name: "AreaChart",
    description: "LineChart with a stronger under-line gradient",
    accent: "text-term-teal",
    group: "data-viz",
    source: "line-chart.tsx",
    demo: "AreaChart",
    api: "Same renderer as LineChart with a brighter default `fill` — the gradient becomes the feature. Shares all props and the shared chart helpers (`lib/custom/chart.ts`).",
    keymap: [
      ["← / h", "Move crosshair left"],
      ["→ / l", "Move crosshair right"],
    ],
    props: [
      { name: "data", type: "number[] | {x,y}[]", default: "[]", description: "Series; auto-indexed when plain numbers" },
      { name: "color", type: "string", default: '"#7dcfff"', description: "Line color" },
      { name: "fill", type: "string", default: '"#24283b"', description: "Gradient end color (brighter than LineChart)" },
      { name: "title", type: "string", default: "-", description: "Optional header row with hi/lo labels" },
      { name: "loading / reveal", type: "boolean / number", default: "false / 1", description: "Shimmer skeleton / clip-reveal" },
      { name: "crosshair / focused", type: "boolean", default: "false / true", description: "Selection + tooltip, keyboard gate" },
    ],
    notes: [
      "LineChart and AreaChart are the same component with different defaults — one source file, two registrations.",
      "Pair with Sparkline for mini/detail chart hierarchies.",
    ],
  },
  {
    slug: "progress-bar",
    name: "ProgressBar",
    description: "Animated progress bar with label and percentage",
    accent: "text-term-cyan",
    group: "feedback",
    source: "progress-bar.tsx",
    demo: "ProgressBar",
    api: "Composition-only component: `<ProgressBar />` builds on `<box>` + `<text>`. No `extend()` registration needed.",
    keymap: [
      ["—", "No keyboard input (display only)"],
      ["value prop", "Drive progress from state or useTimeline"],
    ],
    props: [
      { name: "value", type: "number", default: "-", description: "Current value (clamped to [0, max])" },
      { name: "max", type: "number", default: "100", description: "Maximum value" },
      { name: "width", type: "number", default: "20", description: "Track width in characters" },
      { name: "label", type: "string", default: "-", description: "Optional label on the left of the row" },
      { name: "color", type: "string", default: '"#7aa2f7"', description: "Fill color" },
      { name: "trackColor", type: "string", default: '"#2f3449"', description: "Track color" },
      { name: "percentColor", type: "string", default: '"#565f89"', description: "Percentage text color" },
      { name: "showPercent", type: "boolean", default: "true", description: "Show the percentage value" },
      { name: "variant", type: '"blocks" | "line" | "dots" | "gradient"', default: '"blocks"', description: "Bar rendering style" },
    ],
    notes: [
      "Fill is a nested `<box>` with computed width — the same pattern the system-monitor example uses.",
      "Animate by feeding it state updated from useTimeline's onUpdate, or plain setInterval.",
    ],
    variants: [
      { id: "blocks", label: "blocks", blurb: "Solid background-color fill (default)" },
      { id: "line", label: "line", blurb: "Box-drawing ━/─ track glyphs" },
      { id: "dots", label: "dots", blurb: "Dot-matrix ●/· style" },
      { id: "gradient", label: "gradient", blurb: "Fill lerps toward white across the track" },
    ],
  },
  {
    slug: "sparkline",
    name: "Sparkline",
    description: "Mini time-series chart with gradient fill, dot and reveal",
    accent: "text-term-green",
    group: "data-viz",
    source: "sparkline.tsx",
    demo: "Sparkline",
    api: "Single-row block-glyph chart (▁▂▃▄▅▆▇█). Per-column gradient mixes `fg → fill` by glyph depth; a ● tracks the latest value. No keyboard input.",
    keymap: [["—", "Display only"]],
    props: [
      { name: "data", type: "number[]", default: "[]", description: "Series of values (windowed to width)" },
      { name: "width", type: "number", default: "24", description: "Number of glyphs to render" },
      { name: "fg", type: "string", default: '"#7dcfff"', description: "Line color (glyph top)" },
      { name: "fill", type: "string", default: '"#1a1b26"', description: "Gradient end color (glyph base)" },
      { name: "min / max", type: "number", default: "auto", description: "Optional fixed scale bounds" },
      { name: "reveal", type: "number", default: "1", description: "0..1 reveal progress" },
      { name: "loading", type: "boolean", default: "false", description: "Shimmer sweep skeleton" },
      { name: "dot", type: "boolean", default: "true", description: "● marker on the last revealed column" },
    ],
    notes: [
      "Scales to the last `width` values — feed it a growing array and it slides.",
      "Loading reuses the same traveling-▓ shimmer as LineChart, in one row.",
    ],
  },
  {
    slug: "badge",
    name: "Badge",
    description: "Tone-colored status pill built from box + text",
    accent: "text-term-magenta",
    group: "feedback",
    source: "badge.tsx",
    demo: "Badge",
    api: "Pure presentational component with 7 built-in tones.",
    keymap: [["—", "Display only"]],
    props: [
      { name: "label", type: "string", default: "-", description: "Badge text" },
      { name: "tone", type: "blue | cyan | green | yellow | red | magenta | gray", default: '"blue"', description: "Color pair (bg + fg)" },
      { name: "prefix", type: "string", default: '""', description: "Optional glyph prefix, e.g. '● '" },
    ],
    notes: [
      "Tones are static hex pairs — no runtime color parsing, no allocations.",
      "Compose into status bars or table cells as nested children.",
    ],
  },
  {
    slug: "tree-view",
    name: "TreeView",
    description: "Keyboard-navigable tree with expand/collapse",
    accent: "text-term-yellow",
    group: "input",
    source: "tree-view.tsx",
    demo: "TreeView",
    api: "Recursive flatten of nodes into a flat row list. Keyboard handled via useKeyboard; gate on the `focused` prop.",
    keymap: [
      ["↑ / k", "Move selection up"],
      ["↓ / j", "Move selection down"],
      ["→ / l", "Expand node"],
      ["← / h", "Collapse node, or jump to parent"],
      ["Enter", "Toggle expand + fire onSelect"],
    ],
    props: [
      { name: "nodes", type: "TreeNode[]", default: "-", description: "Root nodes: { name, value?, children? }" },
      { name: "focused", type: "boolean", default: "true", description: "Gate for keyboard handling" },
      { name: "onSelect", type: "(node, path) => void", default: "-", description: "Fired with node + slash path on Enter" },
      { name: "indent", type: "number", default: "2", description: "Indent per depth level" },
      { name: "selectedBackgroundColor", type: "string", default: '"#334455"', description: "Selection row background" },
      { name: "selectedTextColor", type: "string", default: '"#e0af68"', description: "Selection row text color" },
    ],
    notes: [
      "Expanded set is kept in a Set<string> keyed by slash path — cheap and stable across re-renders.",
      "Glyphs: ▾ expanded, ▸ collapsed, · leaf.",
    ],
  },
  {
    slug: "toast",
    name: "Toast",
    description: "Toast provider with queue, tones, and auto-dismiss",
    accent: "text-term-red",
    group: "feedback",
    source: "toast.tsx",
    demo: "Toast",
    api: "Context-based: wrap the app in `<ToastProvider>`, then call `useToasts().push(...)` from anywhere. Auto-dismiss via timers; a per-toast timeline renders the TTL bar.",
    keymap: [
      ["push()", "Append a toast (info | success | warning | error)"],
      ["dismiss(id)", "Remove a toast early"],
    ],
    props: [
      { name: "ToastProvider", type: "children: ReactNode", default: "-", description: "Root provider, renders the toast stack overlay" },
      { name: "push", type: "{ title, message?, tone, duration? }", default: "duration 4000", description: "Returns toast id" },
      { name: "dismiss", type: "(id: number) => void", default: "-", description: "Remove a toast" },
      { name: "ToastItem", type: "interface", default: "-", description: "{ id, title, message?, tone, duration }" },
    ],
    notes: [
      "Timers are cleaned up on unmount — no leaks.",
      "Stack is absolutely positioned top-right, above your app content.",
    ],
  },
  {
    slug: "modal",
    name: "Modal",
    description: "Dimmed overlay dialog with focus on the panel",
    accent: "text-term-blue",
    group: "input",
    source: "modal.tsx",
    demo: "Modal",
    api: "Renders `null` when closed. When open, an absolute full-screen dim box centers a double-bordered panel; the panel grabs focus; esc/q closes.",
    keymap: [
      ["esc / q", "Close the modal"],
      ["(panel)", "Focus moves to the modal panel when opened"],
    ],
    props: [
      { name: "open", type: "boolean", default: "-", description: "Show or hide" },
      { name: "onClose", type: "() => void", default: "-", description: "Called on esc/q" },
      { name: "title", type: "string", default: "-", description: "Optional title row" },
      { name: "width / height", type: "number", default: "46 / 10", description: "Panel size" },
      { name: "borderColor", type: "string", default: '"#7aa2f7"', description: "Panel border color" },
    ],
    notes: [
      "The overlay uses an RGBA color with alpha — OpenTUI renders real dimming, not a static shade.",
      "Combine with ToastProvider: confirmations push toasts, modals ask questions.",
    ],
  },
  {
    slug: "grid",
    name: "Grid",
    description: "Flexbox rows of equal-width cells",
    accent: "text-term-teal",
    group: "layout",
    source: "grid.tsx",
    demo: "Grid",
    api: "Slices `cells` into rows of `columns`; every cell is a box with flexGrow 1, so a row always fills its container width. Pure composition — no layout engine of its own.",
    keymap: [
      ["—", "No keyboard input (layout only)"],
      ["columns prop", "Change column count; cells re-flow"],
    ],
    props: [
      { name: "cells", type: "ReactNode[]", default: "-", description: "Cell contents, row-major order" },
      { name: "columns", type: "number", default: "cells.length", description: "Cells per row; last row may be short" },
      { name: "gap", type: "number", default: "1", description: "Gap between cells and rows" },
      { name: "cellProps", type: "box props", default: "-", description: "Extra props applied to every cell box" },
    ],
    notes: [
      "Sizing is deferred to the parent: give the Grid a width (or let the app root size it) and cells split it evenly.",
      "Short last rows stretch — perfect for dashboards and menu grids.",
    ],
  },
  {
    slug: "divider",
    name: "Divider",
    description: "Horizontal rule with optional label",
    accent: "text-term-cyan",
    group: "layout",
    source: "divider.tsx",
    demo: "Divider",
    api: "A row of two flexGrow boxes with `border: [\"top\"]`, flanking an optional label. One of the few places OpenTUI's side-specific borders earn their keep.",
    keymap: [["—", "Display only"]],
    props: [
      { name: "label", type: "string", default: "-", description: "Text centered on the rule" },
      { name: "color", type: "string", default: '"#2f3449"', description: "Rule color" },
      { name: "labelColor", type: "string", default: '"#565f89"', description: "Label color" },
      { name: "style", type: "single | double | rounded | heavy", default: '"single"', description: "Border style of the rule" },
      { name: "paddingX", type: "number", default: "1", description: "Horizontal padding" },
    ],
    notes: [
      "Uses border side arrays (`border: [\"top\"]`) — available on every OpenTUI box.",
      "Labels help group settings panels: `<Divider label=\"network\" />`.",
    ],
  },
  {
    slug: "textarea",
    name: "Textarea",
    description: "Multiline text input with cursor",
    accent: "text-term-green",
    group: "input",
    source: "textarea.tsx",
    demo: "Textarea",
    api: "A small editor state machine: `lines: string[]` plus a `{ row, col }` cursor. Character keys insert via `key.sequence`, named keys (backspace, return, arrows) edit. Renders at most `rows` lines — no scrollbar yet.",
    keymap: [
      ["chars", "Insert at cursor (key.sequence)"],
      ["return", "Split line"],
      ["backspace / delete", "Delete left / right"],
      ["↑ ↓ ← →", "Move cursor"],
      ["home / end", "Line start / end"],
    ],
    props: [
      { name: "defaultValue", type: "string", default: '""', description: "Initial text" },
      { name: "onChange", type: "(value: string) => void", default: "-", description: "Fired with the full text on every edit" },
      { name: "rows", type: "number", default: "3", description: "Max visible lines" },
      { name: "placeholder", type: "string", default: '""', description: "Shown when empty and unfocused" },
      { name: "focused", type: "boolean", default: "true", description: "Gate for keyboard handling" },
      { name: "cursorFg / cursorBg", type: "string", default: '"#16161e" / "#7dcfff"', description: "Cursor cell colors" },
    ],
    notes: [
      "The cursor renders as an inverted cell mid-line, or a filled block at end-of-line.",
      "Controlled `value` is not (yet) supported — pair with onChange if you need it.",
    ],
  },
  {
    slug: "qrcode",
    name: "QRCode",
    description: "QR code rendered from real bytes",
    accent: "text-term-yellow",
    group: "display",
    source: "qrcode.tsx",
    demo: "QRCode",
    api: "Encodes the input with a real QR encoder (byte mode, EC level L, versions 1–5, best-of-8 masking with penalty scoring) and renders it as ▀▄█ half-blocks. Pair with your terminal's URL-click support to make codes scannable.",
    keymap: [["—", "Display only"]],
    props: [
      { name: "value", type: "string", default: "-", description: "Payload, UTF-8 bytes; max 106 bytes" },
      { name: "fg", type: "string", default: '"#9ece6a"', description: "Dark module color" },
      { name: "bg", type: "string", default: '"#1a1b26"', description: "Light module background" },
      { name: "quiet", type: "number", default: "2", description: "Quiet-zone modules (spec requires 4 for scanners)" },
    ],
    notes: [
      "The encoder (`qr-encoder.ts`) is dependency-free: GF(256) arithmetic, Reed–Solomon EC, pattern placement, mask scoring — the whole spec.",
      "Returns `null` when the payload exceeds 106 bytes instead of rendering garbage.",
      "Scanners usually need a quiet zone of 4 — bump `quiet` if a phone fails to read it.",
    ],
  },
  {
    slug: "bar-chart",
    name: "BarChart",
    description: "Vertical bars with gridlines, value and category labels",
    accent: "text-term-cyan",
    group: "data-viz",
    source: "bar-chart.tsx",
    demo: "BarChart",
    api: "Column bars over a half-block grid (`height*2` pixel resolution). Bars grow from the baseline, lerp `color → fill` by depth, and sit on optional `─` gridlines from niceTicks. Values float above the bar tops, category labels center under each column group.",
    keymap: [["—", "Display only"]],
    props: [
      { name: "data", type: "{ label?, value, color? }[]", default: "-", description: "Bar values; per-bar color overrides `color`" },
      { name: "width / height", type: "number", default: "40 / 9", description: "Chart area in characters" },
      { name: "color / fill", type: "string", default: '"#7dcfff" / "#1a1b26"', description: "Bar color and gradient end" },
      { name: "max", type: "number", default: "auto", description: "Fixed scale top (defaults to max value)" },
      { name: "showValues / showLabels", type: "boolean", default: "true", description: "Value captions and category labels" },
      { name: "gridlines", type: "boolean", default: "true", description: "Nice-tick horizontal gridlines" },
    ],
    notes: [
      "Gridlines only draw on empty cells — bars stay solid.",
      "Label glyphs are clipped to their column group, so long names degrade gracefully.",
    ],
  },
  {
    slug: "pie-chart",
    name: "PieChart",
    description: "Solid disc colored by share with legend",
    accent: "text-term-magenta",
    group: "data-viz",
    source: "pie-chart.tsx",
    demo: "PieChart",
    api: "Every cell inside the disc gets the color of the slice covering its angle (12 o'clock start, clockwise). Rim cells lerp toward white for a subtle edge. Legend renders `■ label %` rows below the disc.",
    keymap: [["—", "Display only"]],
    props: [
      { name: "data", type: "{ label, value, color }[]", default: "-", description: "Slices; share of total drives the angle" },
      { name: "width / height", type: "number", default: "21 / 11", description: "Disc size in characters" },
      { name: "legend", type: "boolean", default: "true", description: "Render the label/percent legend" },
    ],
    notes: [
      "Feeds straight into RingChart — same renderer, different inner radius.",
      "Pair with a muted fill background so slices pop.",
    ],
  },
  {
    slug: "ring-chart",
    name: "RingChart",
    description: "Donut with a centered total and legend",
    accent: "text-term-teal",
    group: "data-viz",
    source: "ring-chart.tsx",
    demo: "RingChart",
    api: "PieChart's renderer with `innerRatio 0.55`: the core is punched out and the total (or any `center` string) is drawn in the hole. The center label is only shown when a center is provided — pass `center=\"\"` to keep it empty.",
    keymap: [["—", "Display only"]],
    props: [
      { name: "data", type: "{ label, value, color }[]", default: "-", description: "Slices" },
      { name: "width / height", type: "number", default: "21 / 11", description: "Donut size" },
      { name: "legend", type: "boolean", default: "true", description: "Legend rows" },
      { name: "center", type: "string", default: "Σ of values", description: "Text in the hole" },
      { name: "centerColor", type: "string", default: '"#c0caf5"', description: "Center text color" },
    ],
    notes: [
      "The center is sized to the hole — long totals get clipped visually.",
      "Great for status dials: green/yellow/red slices + a count in the middle.",
    ],
  },
  {
    slug: "gauge",
    name: "Gauge",
    description: "Semicircle arc with warn/danger zones and needle",
    accent: "text-term-green",
    group: "data-viz",
    source: "gauge.tsx",
    demo: "Gauge",
    api: "Upper-half arc from left to right. The arc is colored per-cell by its value fraction: under `warnAt` base color, under `dangerAt` warn color, else danger color. A bright needle sweeps from the center and a footer row prints `label value/max %`. Value renders as filled arc cells — not a solid track.",
    keymap: [["—", "Display only"]],
    props: [
      { name: "value", type: "number", default: "-", description: "Current value (clamped to min..max)" },
      { name: "min / max", type: "number", default: "0 / 100", description: "Scale bounds" },
      { name: "width / height", type: "number", default: "26 / 9", description: "Arc size" },
      { name: "color / warnColor / dangerColor", type: "string", default: "green / yellow / red", description: "Zone colors" },
      { name: "warnAt / dangerAt", type: "number", default: "0.66 / 0.88", description: "Zone thresholds as fractions" },
      { name: "showTicks", type: "boolean", default: "true", description: "Quarter ticks on the outer edge" },
      { name: "label", type: "string", default: "-", description: "Footer label" },
    ],
    notes: [
      "Zone colors are computed per arc cell, so the frontier is exact — no banded steps.",
      "Needle glyphs are `│` along the radius with a `▌` tip on the arc.",
    ],
  },
  {
    slug: "heatmap",
    name: "Heatmap",
    description: "Background-colored matrix with labels and gradient legend",
    accent: "text-term-yellow",
    group: "data-viz",
    source: "heatmap.tsx",
    demo: "Heatmap",
    api: "Each matrix cell renders as `cellWidth` spaces with a background color interpolated across the `colors` ramp. Row and column labels frame the grid; a gradient legend row prints min/max. Colors stop at 7 points by default (Tokyonight ramp).",
    keymap: [["—", "Display only"]],
    props: [
      { name: "data", type: "number[][]", default: "-", description: "Row-major values" },
      { name: "rowLabels / colLabels", type: "string[]", default: "-", description: "Axis labels; row labels pad the left" },
      { name: "colors", type: "string[]", default: "7-stop ramp", description: "Interpolation stops low→high" },
      { name: "min / max", type: "number", default: "auto", description: "Scale bounds" },
      { name: "cellWidth", type: "number", default: "2", description: "Characters per cell" },
      { name: "legend / legendWidth", type: "boolean / number", default: "true / 10", description: "Legend row and gradient width" },
    ],
    notes: [
      "Background colors are real cell backgrounds — the terminal dims nothing.",
      "Feed live latency numbers and the ramp does the rest.",
    ],
  },
  {
    slug: "candlestick",
    name: "CandlestickChart",
    description: "OHLC candles with wicks, up/down colors and index labels",
    accent: "text-term-red",
    group: "data-viz",
    source: "candlestick.tsx",
    demo: "Candlestick",
    api: "One candle per data point at the column group center. Bodies are `█` with `▀/▄` edges at half-pixel rows, wicks are `│`; body wins over wick on overlap. Green when close ≥ open, red otherwise. Index labels every few candles on the bottom row.",
    keymap: [["—", "Display only"]],
    props: [
      { name: "data", type: "{ open, high, low, close }[]", default: "-", description: "OHLC series" },
      { name: "width / height", type: "number", default: "40 / 10", description: "Chart area" },
      { name: "up / down", type: "string", default: '"#9ece6a" / "#f7768e"', description: "Bullish / bearish body colors" },
      { name: "wick", type: "string", default: '"#7a81a8"', description: "Wick color" },
      { name: "showLabels", type: "boolean", default: "true", description: "Index labels row" },
    ],
    notes: [
      "Scale is computed from high/low across the whole series — candles stay true.",
      "Feed it a rolling window (slice(-n)) to build a live ticker.",
    ],
  },
  {
    slug: "scatter",
    name: "ScatterChart",
    description: "Multi-series dot plot with gridlines and legend",
    accent: "text-term-blue",
    group: "data-viz",
    source: "scatter.tsx",
    demo: "Scatter",
    api: "Points map to cells; `●` per series color. Overlapping points from different series render `✚`. Optional `·` gridlines on both axes, min/max range labels on the bottom row, and a legend with each series' y-range.",
    keymap: [["—", "Display only"]],
    props: [
      { name: "series", type: "{ label, color, points }[]", default: "-", description: "Series with { x, y } points" },
      { name: "width / height", type: "number", default: "40 / 10", description: "Plot area" },
      { name: "minX / maxX / minY / maxY", type: "number", default: "auto", description: "Fixed bounds (auto from data)" },
      { name: "gridlines / legend", type: "boolean", default: "true", description: "Grid and legend rows" },
    ],
    notes: [
      "Bounds default to the union of all series — add fixed bounds to compare frames.",
      "Cluster drift + grids reads like a live correlation plot.",
    ],
  },
  {
    slug: "funnel",
    name: "FunnelChart",
    description: "Centered shrinking bars with per-stage gradient and percent",
    accent: "text-term-red",
    group: "data-viz",
    source: "funnel.tsx",
    demo: "Funnel",
    api: "One row per stage. Bar width scales with `value/max`, centered in the canvas, followed by the stage label and a right-aligned percent. Colors lerp `baseColor → endColor` across stages unless a stage provides its own `color`.",
    keymap: [["—", "Display only"]],
    props: [
      { name: "stages", type: "{ label, value, color? }[]", default: "-", description: "Stages in funnel order" },
      { name: "width", type: "number", default: "42", description: "Canvas width" },
      { name: "showPercent", type: "boolean", default: "true", description: "Right-aligned percent of max" },
      { name: "baseColor / endColor", type: "string", default: "cyan / red", description: "Gradient endpoints" },
    ],
    notes: [
      "Percent is relative to the largest stage, not the first — churn shows honest drop-off.",
      "Swap in `color` per stage for threshold-based coloring.",
    ],
  },
  {
    slug: "agent-spinner",
    name: "AgentSpinner",
    description: "Neomorphic status line with spinner, sub-task and elapsed timer",
    accent: "text-term-green",
    group: "agentic",
    source: "agent-spinner.tsx",
    demo: "AgentSpinner",
    api: "Composition-only. Renders a single beveled panel (light top/left edge, dark bottom/right) around a spinner glyph, label, optional sub text and live ⏱ timer. The `neo.ts` helpers (NEO palette, neoPanel, neoInset, neoFill) power all the agents group components.",
    keymap: [
      ["—", "Display only"],
      ["running prop", "Drives the frame rotation + elapsed timer"],
    ],
    props: [
      { name: "label", type: "string", default: '"thinking"', description: "Status text" },
      { name: "sub", type: "string", default: "-", description: "Dimmed secondary text" },
      { name: "running", type: "boolean", default: "true", description: "Rotate frames + count time" },
      { name: "color", type: "string", default: '"#a5d98f"', description: "Spinner color" },
      { name: "elapsed", type: "boolean", default: "true", description: "Show ⏱ mm:ss" },
      { name: "frames", type: "string[]", default: "braille spinner", description: "Custom frame set" },
      { name: "colors", type: "Partial<NeoColors>", default: "NEO", description: "Override bevel palette" },
    ],
    notes: [
      "Neomorphism in a terminal = 2-tone bevel: ╭ top/left light (light source), ╰ bottom/right dark (shadow).",
      "The same bevel language is shared by StatusBar, ToolCall, ApprovalPrompt, TokenMeter, StepList.",
    ],
  },
  {
    slug: "status-bar",
    name: "StatusBar",
    description: "Agent bottom bar: mode, model, task, clock and token counter",
    accent: "text-term-blue",
    group: "agentic",
    source: "status-bar.tsx",
    demo: "StatusBar",
    api: "Full-width three-row strip: raised top edge, content row, sunken bottom edge. Left segment shows ● mode + model, center task text (auto-truncated), right-aligned clock and tokens.",
    keymap: [["—", "Display only"]],
    props: [
      { name: "mode / model", type: "string", default: '"agent" / model id', description: "Identity segment" },
      { name: "task", type: "string", default: "-", description: "Current task, truncated to fit" },
      { name: "time / tokens", type: "string", default: "-", description: "Right-aligned widgets" },
      { name: "running", type: "boolean", default: "false", description: "Turns ● and mode bright" },
      { name: "width", type: "number", default: "62", description: "Total bar width" },
      { name: "colors", type: "Partial<NeoColors>", default: "NEO", description: "Bevel palette" },
    ],
    notes: [
      "The ● pulse + bright mode segment signal an active agent turn, like opencode's TUI bottom bar.",
      "Feed `time`/`tokens` from your own interval — the bar itself is pure display.",
    ],
  },
  {
    slug: "tool-call",
    name: "ToolCall",
    description: "Invocation card: state glyph, args, duration and collapsible output",
    accent: "text-term-magenta",
    group: "agentic",
    source: "tool-call.tsx",
    demo: "ToolCall",
    api: "Beveled panel per tool invocation. Header row: ▾/▸ chevron, state glyph (· pending, spinner running, ✓ done, ✗ error), tool name, dimmed args, right-aligned ms duration. Enter/Space toggles an output section when focused.",
    keymap: [
      ["return / space", "Expand or collapse output (when focused)"],
      ["state prop", "pending | running | done | error"],
    ],
    props: [
      { name: "name", type: "string", default: "-", description: "Tool name" },
      { name: "args", type: "string", default: "-", description: "Argument summary" },
      { name: "state", type: "ToolState", default: '"pending"', description: "pending | running | done | error" },
      { name: "durationMs", type: "number", default: "-", description: "Right-aligned duration" },
      { name: "output", type: "string[]", default: "[]", description: "Lines under the header when expanded" },
      { name: "expanded / defaultExpanded", type: "boolean", default: "- / false", description: "Controlled or initial expansion" },
      { name: "onToggle / focused", type: "() => void / boolean", default: "- / true", description: "Callback + keyboard gate" },
      { name: "colors", type: "Partial<NeoColors>", default: "NEO", description: "Bevel palette" },
    ],
    notes: [
      "The exact shape of Claude Code / opencode tool invocation logs, restyled as extruded cards.",
      "Map a queue of ToolCalls to render the full tool-calling session.",
    ],
  },
  {
    slug: "approval-prompt",
    name: "ApprovalPrompt",
    description: "Permission dialog with keyboard yes/no and selection state",
    accent: "text-term-yellow",
    group: "agentic",
    source: "approval-prompt.tsx",
    demo: "ApprovalPrompt",
    api: "Beveled confirm dialog: `?` glyph + title, dimmed message, and a [y]es/[n]o key-cap row where the selected cap inverts (light bg, dark fg). Fires `onAnswer(bool)`.",
    keymap: [
      ["y", "Allow (yes)"],
      ["n / esc", "Deny (no)"],
      ["← / → (h / l)", "Move selection between caps"],
      ["enter", "Confirm current selection"],
    ],
    props: [
      { name: "title / message", type: "string", default: '"allow tool?" / -', description: "Dialog copy" },
      { name: "onAnswer", type: "(allow: boolean) => void", default: "-", description: "Result callback" },
      { name: "focused", type: "boolean", default: "true", description: "Keyboard gate" },
      { name: "colors", type: "Partial<NeoColors>", default: "NEO", description: "Bevel palette" },
    ],
    notes: [
      "The key caps reuse the bevel colors — selection reads as a physical key pressed in.",
      "Render it centered over a dimmed overlay (pair with Modal) for a real permission modal.",
    ],
  },
  {
    slug: "token-meter",
    name: "TokenMeter",
    description: "Context window usage bar with zone colors and io stats",
    accent: "text-term-red",
    group: "agentic",
    source: "token-meter.tsx",
    demo: "TokenMeter",
    api: "Raised label row + recessed (inset) track: dark well with the fill as █ bars. Fill color crosses green → yellow at `warnAt` → red at `dangerAt`. Bottom stats row shows ↑input ↓output ☍cache.",
    keymap: [["—", "Display only"]],
    props: [
      { name: "used / total", type: "number", default: "0 / 200000", description: "Window usage" },
      { name: "input / output / cached", type: "number", default: "0", description: "Per-direction token stats" },
      { name: "width", type: "number", default: "34", description: "Track width" },
      { name: "warnAt / dangerAt", type: "number", default: "0.6 / 0.85", description: "Zone thresholds" },
      { name: "color", type: "string", default: '"#a5d98f"', description: "Fill color under warnAt" },
      { name: "colors", type: "Partial<NeoColors>", default: "NEO", description: "Bevel palette" },
    ],
    notes: [
      "Inset track is the recessed twin of the raised panels — light/dark edges flipped.",
      "At 85% the fill goes red: context pressure at a glance, LSP-server style.",
    ],
  },
  {
    slug: "step-list",
    name: "StepList",
    description: "Session plan tracker: pending → running → done with live spinner",
    accent: "text-term-cyan",
    group: "agentic",
    source: "step-list.tsx",
    demo: "StepList",
    api: "Beveled list container with optional title row. Each step: state glyph (· pending, braille spinner running, ✓ green, ✗ red, – skipped), label, right-aligned detail. `indent` adds a sub-step gutter.",
    keymap: [["—", "Display only"]],
    props: [
      { name: "title", type: "string", default: "-", description: "Header row inside the panel" },
      { name: "steps", type: "{ label, state, detail?, indent? }[]", default: "[]", description: "Plan rows" },
      { name: "color", type: "string", default: '"#a5d98f"', description: "Running spinner color" },
      { name: "colors", type: "Partial<NeoColors>", default: "NEO", description: "Bevel palette" },
    ],
    notes: [
      "Drive states from your task runner — the only moving part is the running row's spinner.",
      "A full plan read as beveled steps is the agentic-pairing of ProgressBar.",
    ],
  },
];

export const customBySlug = Object.fromEntries(
  customComponents.map((c) => [c.slug, c]),
);

/** Components in canonical category order (used for prev/next navigation). */
export const orderedCustomComponents: CustomMeta[] = CATEGORIES.flatMap((cat) =>
  customComponents.filter((c) => c.group === cat.id),
);
